#!/bin/bash
 
if [ ! -f ./env-vars ]; then
  echo "Missing ./env-vars (one required variable name per line)"
  exit 1
fi

if [ -z ${NODE_ENV} ]; then NODE_ENV=development; fi

ENV_PATH="$(dirname -- "${BASH_SOURCE[0]}")/.."

ALL_VARS=$(cat $ENV_PATH/.env $ENV_PATH/.env.$NODE_ENV $ENV_PATH/.env.local $ENV_PATH/.env.$NODE_ENV.local 2> /dev/null | grep -v '^#')

while IFS= read -r var_name; do
  echo "$ALL_VARS" | grep -w "$var_name" | tail -1
done < ./env-vars
